n = int(input('digite 3 numeros de 1 a 10, lhe direi qual maior e o menor entre eles: primeiro numero: '))
n2 = int(input('segundo numero: '))
n3 = int(input('terceiro numero: '))
ln = [n,n2,n3]
print('o maior numero e {}, e o menor e {}, !!'.format(max(ln),min(ln)))
#n1 = int(input('digite primeiro numero: '))
#n2 = int(input('digite segundo numero: '))
#n3 = int(input('digite terceiro numero: '))
#print('o maior numero é', max(n1, n2, n3))
#print('o menor numero é', min(n1, n2, n3))
